# Generated by Django 6.0 on 2025-12-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="qr_image",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
